config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  devise_for :users

  namespace :admin do
      resources :doctors
      resources :users
      resources :categories
      resources :appointments

      root to: "doctors#index"
    end

  resources :categories, only: [:show, :index]
  resources :doctors, only: [:show, :index]
  resources :users, only: [:show]
  resources :appointments, only: [:show, :edit, :new, :create, :update]

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/welcome/index_helper.rb
module Welcome::IndexHelper
end

app/views/welcome/index.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>Медицинский центр Здоровье</h1>
      <hr>
    </div>
    <% unless current_user.present? || current_doctor.present? %>
    <div class="col-md-3">
      <%= link_to "Войти как пользователь", new_user_session_path, class:"btn btn-success" %>
    </div>
    <div class="col-md-2">
      <%= link_to "Войти как доктор", new_doctor_session_path, class: "btn btn-danger" %><br>
    </div>
    <% end %>
    <br><br><br>
    <div class="col-md-12">
      <h2>Выбор доктора по категории:</h2>
      <% Category.all.each do |category| %>
        <%= link_to "#{category.name}", category_path(category), class: "btn btn-info"%>
      <% end %>
      <br><br>
      <h4><%= link_to "Список всех докторов", doctors_path, class: "btn btn-warning" %></h4>
    </div>
  </div>
</div>