config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  devise_for :users

  namespace :admin do
      resources :doctors
      resources :users
      resources :categories
      resources :appointments

      root to: "doctors#index"
    end

  resources :categories, only: [:show, :index]
  resources :doctors, only: [:show, :index]
  resources :users, only: [:show]
  resources :appointments, only: [:show, :edit, :new, :create, :update]

  root 'welcome#index'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
  validate :limit_appointment
  validates_uniqueness_of :user_id, :scope => :doctor_id, if: Proc.new { |appointment| appointment.status }

  private

  def limit_appointment
    if doctor.appointments.where(status: true).size > 10
      errors.add(:doctor_id, "has more than 10 open appointments")
    end
  end
end

app/controllers/admin/appointments_controller.rb
module Admin
  class AppointmentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to appointment_path(@appointment)
    else
      redirect_to doctor_path(@appointment.doctor), alert: "You are already registered or the appointment with this doctor is full"
    end
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to appointment_path(@appointment)
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointment_path
  end

  private
  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:user_id, :doctor_id, :status, :recommendation)
  end
end

app/views/appointments/_appointment.html.erb
<tr>
  <td><%= appointment.doctor.name %> - <%= appointment.user.name %></td>
  <td><%= link_to 'Показать', appointment %></td>
  <% if can? :update, appointment %><td><%= link_to 'Редактировать', edit_appointment_path(appointment), class: "btn btn-primary" %></td> |<%end%>
  <% if can? :destroy, appointment %><td><%= link_to 'Удалить', appointment, method: :delete, data: { confirm: 'Вы уверены?' } %></td> | <%end%>
</tr>

app/views/appointments/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_with(model: @appointment, local: true) do |form| %>

      <%= render 'common/errors', resource: @appointment %>

      <p><div class="form-group">
        <%= form.label :user %>
        <%= form.collection_select :user_id, User.all, :id, :name, {}, {class: "form-control"} %>
      </div></p>

      <p><div class="form-group">
        <%= form.label :doctor %>
        <%= form.collection_select :doctor_id, Doctor.all, :id, :name, {}, {class: "form-control"} %>
      </div></p>

      <p>
        <% unless @appointment.new_record? %>
          <div class="field">
            <%= form.label :recommendation, "Описание" %>
            <%= form.text_area :recommendation,
              rows: 13,
              cols: 50 ,
              maxlength: 240,
              autocomplete: :off, class:"form-control" %>
          </div>
        <% else %>
          <% @appointment.status = true %>
          <%= form.hidden_field :status %>
        <% end %>
      </p>

      <div class="actions">
        <%= form.submit "#{ @appointment.new_record? ? 'Создать' : 'Изменить' }", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/appointments/edit.html.erb
<h1 class="text-center">Изменить запись</h1>

<%= render 'form' %>

app/views/appointments/index.html.erb
<h1>Список записей</h1>
<table>
  <thead>
    <tr>
      <th>Записи</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

  <%= render @appointments %>

  </tbody>
</table>

app/views/appointments/new.html.erb
<h1>Добавить запись</h1>

<%= render 'form' %>

app/views/appointments/show.html.erb
<div class="container">
  <div class="text-center">
    <h1>Запись номер <%= @appointment.id %></h1>
  </div>
  <h3>К доктору: <%= @appointment.doctor.name %></h3>
  <h3>Пользователь: <%= @appointment.user.name %></h3>
  <h4>Статус записи: <%= @appointment.status ? "Запись открыта" : "Запись закрыта" %></h4>
  <br><br><br>
  <h2>Рекомендации:<br>
    <% if @appointment.recommendation.present? %>
      <%= @appointment.recommendation %>
    <% else %>
      <p><h4>Пока нет никаких рекомендаций</h4></p>
    <% end %>
  </h2>
  <br><br><br>

  <% if current_doctor.present? %>
    <div class="field">
      <% if (can? :update, @appointment) && @appointment.status == true %>
        <%= form_with(model: @appointment, local: true) do |form| %>
          <%= form.text_area :recommendation,
            rows: 13,
            cols: 50 ,
            maxlength: 240,
            autocomplete: :off %>
          <% @appointment.status = false %>
          <%= form.hidden_field :status, value: @appointment.status %>
          <br>
          <%= form.submit "Добавить", class: "btn bnt-info" %>
        <% end %>
      <% else %>
        <% if can? :update, @appointment %><%= link_to "Редактировать", edit_appointment_path(@appointment), class: "btn btn-primary"%><% end %>
      <% end %>
    </div>
  <% end %>
  <br>
  <%= link_to "На главную", root_path, class: "btn btn-primary" %>
  <%= link_to "К списку врачей", doctors_path, class: "btn btn-primary" %>
</div>