config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  devise_for :users

  namespace :admin do
      resources :doctors
      resources :users
      resources :categories
      resources :appointments

      root to: "doctors#index"
    end

  resources :categories, only: [:show, :index]
  resources :doctors, only: [:show, :index]
  resources :users, only: [:show]
  resources :appointments, only: [:show, :edit, :new, :create, :update]

  root 'welcome#index'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates_length_of :name, maximum: 25
  validates :name, uniqueness: { scope: :doctors }

  has_many :doctors

end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_category.html.erb
<tr>
  <td><%= link_to "#{category.name}", category_path(category), class: "btn btn-light" %></td>
  <% if can? :update, category %><td><%= link_to 'Редактировать', edit_admin_category_path(category), class: "btn btn-primary" %></td><%end%>
  <% if can? :destroy, Category %><td><%= link_to 'Удалить', category, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-primary" %></td><%end%>
</tr>

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |form| %>

  <%= render 'common/errors', resource: @category %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <p>
    <div class="actions">
      <%= form.submit "#{ @category.new_record? ? 'Создать' : 'Изменить' }" %>
    </div>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Изменить категорию</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center">Список категорий</h1>
<div class="container">
  <div class="row">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Название категории</th>
        </tr>
      </thead>
      <tbody>

      <%= render @categories %>

      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<h1>Добавить категорию</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container">
  <h1 class="text-center">Категория: <%= @category.name %></h1>
  <h2>Список докторов</h2>

  <table class="table table-striped">
    <thead>
      <tr>
      <th>Ф.И.О</th>
      <th></th>
      </tr>
    </thead>
    <tbody>
      <% @category.doctors.each do |doctor| %>
        <tr>
          <td><%= link_to "#{doctor.name}", doctor_path(doctor), class: "btn btn-light" %></td>
          <td>
            <% if current_user.present? %>
            <%= form_with(model: Appointment.new, local: true) do |form| %>
            <%= form.hidden_field :user_id, value: current_user.id %>
            <%= form.hidden_field :doctor_id, value: doctor.id %>
            <%= form.submit "Записаться", class: "btn btn-success"%>
            <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Назад", root_path, class: "btn btn-primary" %>
</div>