config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  devise_for :users

  namespace :admin do
      resources :doctors
      resources :users
      resources :categories
      resources :appointments

      root to: "doctors#index"
    end

  resources :categories, only: [:show, :index]
  resources :doctors, only: [:show, :index]
  resources :users, only: [:show]
  resources :appointments, only: [:show, :edit, :new, :create, :update]

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="container-fluid bg-info">
    <nav class="navbar navbar-expand-lg navbar-light bg-info">

      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Мед центр Здоровье", root_path, class: "navbar-brand text-light" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Главная", root_path, class: "nav-link text-light" %>
        </li>
        <% if current_user.present? %>
          <li class="nav-item active">
            <% if can? :read, User %><%= link_to "личный кабинет", user_path(current_user), class: "nav-link text-light" %> <%end%>
          </li>
          <li class="nav-item">
            <%= link_to "Категории врачей", categories_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "Выйти", destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Администратор", admin_root_path, class: "nav-link text-light"%>
            </li>
          <% end %>
        <% elsif current_doctor.present? %>
          <li class="nav-item">
            <% if can? :read, Doctor %><%= link_to "личный кабинет", doctor_path(current_doctor), class: "nav-link text-light" %> <%end%>
          </li>
          <li class="nav-item">
            <%= link_to "Выйти", destroy_doctor_session_path, method: :delete, class: "nav-link text-light"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Войти", new_user_session_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "Войти как доктор", new_doctor_session_path, class: "nav-link text-light" %>
          </li>
        <% end %>
      </ul>
  </nav>
  </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= flash[:alert] %></p>
    <%= cloudinary_js_config %>

    <%= yield %>

  </body>
</html>